### ISSUE TITLE
please add license and copyright statement

### ISSUE THREAD

**Issue by onlyjob** [totten/ca_config#1]
Please add full text of the license as well as copyright statement like

```
Copyright 2012-2013 Tim Otten <totten@example.com>
```

Thank you.

**Comment by totten** [comment]
Fixed by  7a51033

**Comment by onlyjob** [comment]
Nice. Thank you.

**Comment by onlyjob** [comment]
Actually it would be best if you could also include copyright statement and short license name (as well as link to the license) to `*.php` files. This will be useful for projects like CiviCRM where your software is bundled within source tree. Thanks.
