### ISSUE TITLE
PHP 8.2 support

### ISSUE THREAD

**Issue by braders** [totten/ca_config#3]
In CiviCRM some tests are failing on PHP8.2 like so:

```
CRM_Utils_HttpClientTest::testFetchHttps_invalid_verify
Creation of dynamic property CA_Config_Curl::$enableSSL is deprecated

/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/vendor/totten/ca-config/src/CA/Config/Curl.php:85
/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/vendor/totten/ca-config/src/CA/Config/Curl.php:79
/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/CRM/Utils/HttpClient.php:179
/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/CRM/Utils/HttpClient.php:75
/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/tests/phpunit/CRM/Utils/HttpClientTest.php:59
/home/jenkins/bknix-edge/build/build-1/web/sites/all/modules/civicrm/tests/phpunit/CiviTest/CiviUnitTestCase.php:235
/home/jenkins/bknix-edge/extern/phpunit8/phpunit8.phar:1721
```

I think the following properties are currently dynamic, but can be declared:

- `CA_Config_Curl->enableSSL`
- `CA_Config_Curl->verifyPeer`
- `CA_Config_Curl->caFile`
- `CA_Config_Stream->enableSSL`
- `CA_Config_Stream->verifyPeer`
- `CA_Config_Stream->caFile`

It's possible there are others I've missed.

**Comment by totten** [comment]
PR #4 should resolve that "dynamic property" issue.

**Comment by totten** [comment]
@seamuslee001 @braders New release tagged as v23.07.0. Also includes updated `cacert.pem` and some fixes for the `ca_config.git:tests/` suite.
